[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake", "bun"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bunx prisma generate"]

[start]
cmd = "bunx tsx src/index.ts"
